version: '3'
services:

  backend:
    build: ./
    command: ./main
    container_name: 'backend'  # Удалите пробел здесь
    environment:
      - PORT=8080
      - TIMEOUT_SECONDS=200
      - HOST=db
      - DBPORT=5432
      - DBUSER = postgres
      - DBPASSWORD=qwerty
      - DBSSLMODE = disable
      - DBNAME = test_case
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
 