version: '3.8'
services:

  backend:
    image: xapsiel3301/todo
    container_name: 'backend'  # Удалите пробел здесь
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres  
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - net
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net
volumes:
  db:
    driver: local

networks:
  net:
    driver: bridge